
package net.webservicex.goldsilver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * THE LONDON GOLD & SILVER FIXINGS:	The Fixings are an open process at which market participants can transact business on the basis of a single quoted price. Orders can be changed throughout the proceedings as the price is moved higher and lower until such time as buyers' and sellers' orders are satisfied and the price is said to be 'fixed'. 	The fixings are the internationally published benchmarks for precious metals. They are fully transparent and are therefore used to deal in large amounts, or to achieve the accepted average price of the metal. As a benchmark, many other financial instruments are priced off the fixing, including cash-settled swaps and options. The silver fixing started in 1897 and the gold fixing in 1919. 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LondonGoldAndSilverFix", targetNamespace = "http://www.webservicex.net", wsdlLocation = "http://www.webservicex.net/LondonGoldFix.asmx?WSDL")
public class LondonGoldAndSilverFix
    extends Service
{

    private final static URL LONDONGOLDANDSILVERFIX_WSDL_LOCATION;
    private final static WebServiceException LONDONGOLDANDSILVERFIX_EXCEPTION;
    private final static QName LONDONGOLDANDSILVERFIX_QNAME = new QName("http://www.webservicex.net", "LondonGoldAndSilverFix");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.webservicex.net/LondonGoldFix.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LONDONGOLDANDSILVERFIX_WSDL_LOCATION = url;
        LONDONGOLDANDSILVERFIX_EXCEPTION = e;
    }

    public LondonGoldAndSilverFix() {
        super(__getWsdlLocation(), LONDONGOLDANDSILVERFIX_QNAME);
    }

    public LondonGoldAndSilverFix(WebServiceFeature... features) {
        super(__getWsdlLocation(), LONDONGOLDANDSILVERFIX_QNAME, features);
    }

    public LondonGoldAndSilverFix(URL wsdlLocation) {
        super(wsdlLocation, LONDONGOLDANDSILVERFIX_QNAME);
    }

    public LondonGoldAndSilverFix(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LONDONGOLDANDSILVERFIX_QNAME, features);
    }

    public LondonGoldAndSilverFix(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LondonGoldAndSilverFix(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LondonGoldAndSilverFixSoap
     */
    @WebEndpoint(name = "LondonGoldAndSilverFixSoap")
    public LondonGoldAndSilverFixSoap getLondonGoldAndSilverFixSoap() {
        return super.getPort(new QName("http://www.webservicex.net", "LondonGoldAndSilverFixSoap"), LondonGoldAndSilverFixSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LondonGoldAndSilverFixSoap
     */
    @WebEndpoint(name = "LondonGoldAndSilverFixSoap")
    public LondonGoldAndSilverFixSoap getLondonGoldAndSilverFixSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webservicex.net", "LondonGoldAndSilverFixSoap"), LondonGoldAndSilverFixSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LONDONGOLDANDSILVERFIX_EXCEPTION!= null) {
            throw LONDONGOLDANDSILVERFIX_EXCEPTION;
        }
        return LONDONGOLDANDSILVERFIX_WSDL_LOCATION;
    }

}
