
package net.webservicex.goldsilver;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LondonGoldAndSilverFixSoap", targetNamespace = "http://www.webservicex.net")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LondonGoldAndSilverFixSoap {


    /**
     * Get London Gold and Silver fixings
     * 
     * @return
     *     returns net.webservicex.LondonMarketData
     */
    @WebMethod(operationName = "GetLondonGoldAndSilverFix", action = "http://www.webservicex.net/GetLondonGoldAndSilverFix")
    @WebResult(name = "GetLondonGoldAndSilverFixResult", targetNamespace = "http://www.webservicex.net")
    @RequestWrapper(localName = "GetLondonGoldAndSilverFix", targetNamespace = "http://www.webservicex.net", className = "net.webservicex.GetLondonGoldAndSilverFix")
    @ResponseWrapper(localName = "GetLondonGoldAndSilverFixResponse", targetNamespace = "http://www.webservicex.net", className = "net.webservicex.GetLondonGoldAndSilverFixResponse")
    public LondonMarketData getLondonGoldAndSilverFix();

}
